
    version: '3.8'

    services:
      # Service pour l'application Spring Boot
      foyer-app:
        image: firas669/tp-foyer-5.0.0 # Use the pushed image
        ports:
          - "8089:8089"
        depends_on:
          mysql-db:
            condition: service_healthy  # Wait for MySQL to be healthy
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: rootpassword
        networks:
          - my-network  # Specify the network

      # Service pour la base de données MySQL
      mysql-db:
        image: mysql:5.7  # Use MySQL 5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword  # Set MySQL root password
          MYSQL_DATABASE: db  # Database name
        ports:
          - "3306:3306"  # Expose MySQL port
        volumes:
          - mysql_data:/var/lib/mysql  # Persist MySQL data
        networks:
          - my-network  # Specify the network
        healthcheck: # Add health check for MySQL
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
          interval: 5s
          timeout: 10s
          retries: 5

    volumes:
      mysql_data:

    networks:
      my-network:  # Define the custom network